# Generated by Django 5.0.3 on 2024-03-17 19:33

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userpasswordresetcode',
            options={'ordering': ['-id'], 'verbose_name': 'Password Reset Code', 'verbose_name_plural': 'Password Reset Codes'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='User joined date.', verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='User Deleted Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User is active or not. If not, user cannot login to the system.', verbose_name='User Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='User last login date.', null=True, verbose_name='Last Login Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permission',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Manager'), ('member', 'Member')], default='member', help_text='User permission group. Superuser can access all of the system. Manager can access only admin panel.', max_length=20, verbose_name='User Permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='30 Characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='userpasswordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userpasswordresetcode',
            name='reset_code',
            field=models.CharField(max_length=120, verbose_name='User Password Reset Code'),
        ),
        migrations.AlterField(
            model_name='userpasswordresetcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_code', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
