# Generated by Django 5.0.3 on 2024-03-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status_alter_booking_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingRoom',
        ),
    ]
